const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Timer,
		C3.Plugins.AJAX,
		C3.Plugins.Internationalization,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.Dictionary,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Arr.Exps.CurZ,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Exps.int,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Json.Exps.GetAsBeautifiedString,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Cnds.HasTags,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetHeight,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.AdvancedRandom.Exps.WeightedByName,
		C3.Plugins.TiledBg.Exps.BBoxMidX,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Internationalization.Exps.Locale,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.System.Exps.wallclocktime,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Acts.SetLayerForceOwnTexture,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.RemoveAllDynamicLayers,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.JavaScriptInEvents.EsMain_Event90_Act1,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Main_Bar_BG: 0},
	{PopUp_Ribbon: 0},
	{PopUp_infoBG: 0},
	{PopUp_Chest: 0},
	{number: 0},
	{slot: 0},
	{type: 0},
	{girlsIcon: 0},
	{BG: 0},
	{Marker: 0},
	{state: 0},
	{Tween: 0},
	{Rotate: 0},
	{Timer: 0},
	{wheel: 0},
	{Sprite: 0},
	{AJAX: 0},
	{Internationalization: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{AdvancedRandom: 0},
	{BG_Layer: 0},
	{tab_bg: 0},
	{destroyArray: 0},
	{poleArray: 0},
	{saveGamePoleStateArray: 0},
	{saveGameDragStateArray2: 0},
	{getJSON: 0},
	{postJSON: 0},
	{serverTimestampJSON: 0},
	{storyJSON: 0},
	{storyLanguageJSON: 0},
	{storyListJSON: 0},
	{enableGirlsJSON: 0},
	{homeListJSON: 0},
	{girlsDefaultDataJSON: 0},
	{disableGirlsJSON: 0},
	{homeSelectJSON: 0},
	{giftScoreJSON: 0},
	{girlsSaveDataJSON: 0},
	{languageCodeJSON: 0},
	{languageJSON: 0},
	{mainJSON: 0},
	{saveVariable: 0},
	{wheelRewardJSON: 0},
	{width_: 0},
	{height_: 0},
	{active: 0},
	{count_: 0},
	{tag: 0},
	{button: 0},
	{SpriteFont: 0},
	{noTranslate: 0},
	{uppercase: 0},
	{Text: 0},
	{Load_Bar_Back: 0},
	{Load_Bar_Top: 0},
	{popUpBoard: 0},
	{popUpBoard2: 0},
	{popUpBoard2Back: 0},
	{buttonIcon: 0},
	{popUp: 0},
	{girl0: 0},
	{x_1: 0},
	{y_1: 0},
	{drag: 0},
	{block: 0},
	{x_: 0},
	{y_: 0},
	{empty: 0},
	{pole: 0},
	{spawner: 0},
	{DragDrop: 0},
	{boardWindow: 0},
	{size: 0},
	{scroll: 0},
	{swipe: 0},
	{GirlsDict: 0},
	{Pin: 0},
	{Gifts_All: 0},
	{BG_Location: 0},
	{Spin_Icon: 0},
	{Line_Horizontal: 0},
	{ЗАГЛУШКА: 0},
	{TextInput: 0},
	{Button2: 0},
	{chatMessageRight: 0},
	{chatMessageLeft: 0},
	{selectStory: 0},
	{girlsImage: 0},
	{storyIcons: 0},
	{page: 0},
	{shopJSON: 0},
	{wheelWinNumberArray: 0},
	{shopItems: 0},
	{shopBlockBackground: 0},
	{currency: 0},
	{shopImage: 0},
	{popUpBoardFam: 0},
	{chatMessageBackground: 0},
	{girlsMessageImage: 0},
	{blockFam: 0},
	{overlapingCount: 0},
	{overlapingCountNeed: 0},
	{distance_: 0},
	{x_count: 0},
	{y_count: 0},
	{gameOver: 0},
	{gameStep: 0},
	{boost: 0},
	{twoBlock: 0},
	{drop: 0},
	{x: 0},
	{y: 0},
	{xTween: 0},
	{yTween: 0},
	{destroyCount: 0},
	{compareNumber: 0},
	{x1: 0},
	{y1: 0},
	{count: 0},
	{loopindex1: 0},
	{addSize: 0},
	{blockNumber: 0},
	{loading_Progress: 0},
	{LoadBar_Long: 0},
	{getMainData: 0},
	{maxLoadingProgress: 0},
	{getUserServerData: 0},
	{CurrentLanguage: 0},
	{totalDiamonds: 0},
	{homeSelect: 0},
	{home: 0},
	{allMessagesSize: 0},
	{imageHeight: 0},
	{messagesDistance: 0},
	{fullscreenImage: 0},
	{messageSound: 0},
	{chatStep: 0},
	{pos: 0},
	{loadStoryProgress: 0},
	{storyLoadCompleted: 0},
	{animationName: 0},
	{score: 0},
	{gift: 0},
	{shopLayer: 0},
	{layer: 0},
	{quantityInColumn: 0},
	{width: 0},
	{shopBlockPosition: 0},
	{shopItemCount: 0},
	{row: 0},
	{column: 0},
	{startPosition: 0},
	{WinningNumber: 0},
	{WinningGirl: 0},
	{itemCount: 0},
	{createRandomRullet: 0},
	{maxSpeedRotate: 0},
	{rouletteWheel: 0},
	{rotateCount: 0},
	{wheelSize: 0},
	{cef: 0},
	{TelegramID: 0},
	{language: 0},
	{popUpCount: 0},
	{activeLayer: 0},
	{serverURL: 0},
	{currencyNameCoins: 0},
	{currencyNameDiamond: 0},
	{timeNow: 0},
	{girlNumber: 0},
	{girlSelect: 0},
	{girlCount: 0},
	{activeMenuName: 0},
	{chatNumber: 0},
	{girlArrayName: 0},
	{girlsEnableListName: 0},
	{text: 0},
	{serverTimeOld: 0},
	{differenceTime: 0},
	{getParam: 0},
	{visibleBack: 0},
	{all: 0},
	{noAnimation: 0},
	{substructVolume: 0},
	{name: 0},
	{mix: 0},
	{notEnoughType: 0},
	{notEnoughCount: 0},
	{set: 0},
	{save: 0},
	{saveToServer: 0},
	{hm: 0},
	{hms: 0},
	{ms: 0},
	{timeInSecond: 0},
	{mouseScrollSpeed: 0},
	{keyBoarsScrollSpeed: 0},
	{setSize: 0},
	{addPosition: 0},
	{girlKey: 0}
];

self.InstanceType = {
	Main_Bar_BG: class extends self.ISpriteInstance {},
	PopUp_Ribbon: class extends self.ISpriteInstance {},
	PopUp_infoBG: class extends self.ISpriteInstance {},
	PopUp_Chest: class extends self.ISpriteInstance {},
	slot: class extends self.ISpriteInstance {},
	girlsIcon: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	wheel: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Internationalization: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	BG_Layer: class extends self.ISpriteInstance {},
	tab_bg: class extends self.ISpriteInstance {},
	destroyArray: class extends self.IArrayInstance {},
	poleArray: class extends self.IArrayInstance {},
	saveGamePoleStateArray: class extends self.IArrayInstance {},
	saveGameDragStateArray2: class extends self.IArrayInstance {},
	getJSON: class extends self.IJSONInstance {},
	postJSON: class extends self.IJSONInstance {},
	serverTimestampJSON: class extends self.IJSONInstance {},
	storyJSON: class extends self.IJSONInstance {},
	storyLanguageJSON: class extends self.IJSONInstance {},
	storyListJSON: class extends self.IJSONInstance {},
	enableGirlsJSON: class extends self.IJSONInstance {},
	homeListJSON: class extends self.IJSONInstance {},
	girlsDefaultDataJSON: class extends self.IJSONInstance {},
	disableGirlsJSON: class extends self.IJSONInstance {},
	homeSelectJSON: class extends self.IJSONInstance {},
	giftScoreJSON: class extends self.IJSONInstance {},
	girlsSaveDataJSON: class extends self.IJSONInstance {},
	languageCodeJSON: class extends self.IJSONInstance {},
	languageJSON: class extends self.IJSONInstance {},
	mainJSON: class extends self.IJSONInstance {},
	saveVariable: class extends self.IDictionaryInstance {},
	wheelRewardJSON: class extends self.IJSONInstance {},
	button: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	Load_Bar_Back: class extends self.ITiledBackgroundInstance {},
	Load_Bar_Top: class extends self.ITiledBackgroundInstance {},
	popUpBoard: class extends self.IWorldInstance {},
	popUpBoard2: class extends self.IWorldInstance {},
	popUpBoard2Back: class extends self.IWorldInstance {},
	buttonIcon: class extends self.ISpriteInstance {},
	popUp: class extends self.ISpriteInstance {},
	girl0: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	pole: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	drag: class extends self.ISpriteInstance {},
	boardWindow: class extends self.ITiledBackgroundInstance {},
	swipe: class extends self.ITiledBackgroundInstance {},
	GirlsDict: class extends self.IDictionaryInstance {},
	Gifts_All: class extends self.ISpriteInstance {},
	BG_Location: class extends self.ISpriteInstance {},
	Spin_Icon: class extends self.ISpriteInstance {},
	Line_Horizontal: class extends self.ISpriteInstance {},
	ЗАГЛУШКА: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Button2: class extends self.IButtonInstance {},
	chatMessageRight: class extends self.IWorldInstance {},
	chatMessageLeft: class extends self.IWorldInstance {},
	selectStory: class extends self.IWorldInstance {},
	girlsImage: class extends self.ISpriteInstance {},
	storyIcons: class extends self.ISpriteInstance {},
	page: class extends self.ISpriteInstance {},
	shopJSON: class extends self.IJSONInstance {},
	wheelWinNumberArray: class extends self.IArrayInstance {},
	shopItems: class extends self.ISpriteInstance {},
	shopBlockBackground: class extends self.IWorldInstance {},
	currency: class extends self.ISpriteInstance {},
	shopImage: class extends self.ISpriteInstance {},
	popUpBoardFam: class extends self.IWorldInstance {},
	chatMessageBackground: class extends self.IWorldInstance {},
	girlsMessageImage: class extends self.ISpriteInstance {},
	blockFam: class extends self.ISpriteInstance {}
}