const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.AJAX,
		C3.Plugins.Internationalization,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Exps.int,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Internationalization.Exps.Locale,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.System.Exps.wallclocktime,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Acts.SetLayerForceOwnTexture,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.RemoveAllDynamicLayers,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.JavaScriptInEvents.EsMain_Event86_Act1,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Main_Bar_BG: 0},
	{PopUp_Ribbon: 0},
	{PopUp_infoBG: 0},
	{PopUp_Chest: 0},
	{PopUp_Gift_Placeholder: 0},
	{PopUp_Girl_Ava: 0},
	{BG: 0},
	{Marker: 0},
	{Tween: 0},
	{Roulette: 0},
	{Sprite: 0},
	{AJAX: 0},
	{Internationalization: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{BG_Layer: 0},
	{tab_bg: 0},
	{saveVariable: 0},
	{postJSON: 0},
	{getJSON: 0},
	{mainJSON: 0},
	{languageCodeJSON: 0},
	{serverTimestampJSON: 0},
	{languageJSON: 0},
	{type: 0},
	{width_: 0},
	{height_: 0},
	{active: 0},
	{button: 0},
	{number: 0},
	{SpriteFont: 0},
	{noTranslate: 0},
	{uppercase: 0},
	{Text: 0},
	{Load_Bar_Back: 0},
	{Load_Bar_Top: 0},
	{popUpBoard: 0},
	{popUpBoard2: 0},
	{buttonIcon: 0},
	{popUp: 0},
	{GirlsDict: 0},
	{Pin: 0},
	{Gifts_All: 0},
	{Gifts_All_PopUp: 0},
	{BG_Location: 0},
	{Ref_Lang: 0},
	{Ref_Settings: 0},
	{Spin_Icon: 0},
	{Line_Horizontal: 0},
	{ЗАГЛУШКА: 0},
	{Ref_Girls: 0},
	{Anim_Test: 0},
	{AnimaTest: 0},
	{TEstAnim: 0},
	{TextInput: 0},
	{Button2: 0},
	{Pin2: 0},
	{Pop_Up: 0},
	{Pop_Up_Mask: 0},
	{loading_Progress: 0},
	{LoadBar_Long: 0},
	{getMainData: 0},
	{maxLoadingProgress: 0},
	{getUserServerData: 0},
	{CurrentLanguage: 0},
	{totalDiamonds: 0},
	{TelegramID: 0},
	{language: 0},
	{popUpCount: 0},
	{activeLayer: 0},
	{serverURL: 0},
	{currencyNameCoins: 0},
	{currencyNameDiamond: 0},
	{timeNow: 0},
	{text: 0},
	{serverTimeOld: 0},
	{differenceTime: 0},
	{getParam: 0},
	{all: 0},
	{substructVolume: 0},
	{name: 0},
	{mix: 0},
	{notEnoughType: 0},
	{notEnoughCount: 0},
	{currency: 0},
	{count: 0},
	{set: 0},
	{save: 0},
	{saveToServer: 0},
	{hm: 0},
	{hms: 0},
	{ms: 0},
	{timeInSecond: 0}
];

self.InstanceType = {
	Main_Bar_BG: class extends self.ISpriteInstance {},
	PopUp_Ribbon: class extends self.ISpriteInstance {},
	PopUp_infoBG: class extends self.ISpriteInstance {},
	PopUp_Chest: class extends self.ISpriteInstance {},
	PopUp_Gift_Placeholder: class extends self.ISpriteInstance {},
	PopUp_Girl_Ava: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	Roulette: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Internationalization: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BG_Layer: class extends self.ISpriteInstance {},
	tab_bg: class extends self.ISpriteInstance {},
	saveVariable: class extends self.IDictionaryInstance {},
	postJSON: class extends self.IJSONInstance {},
	getJSON: class extends self.IJSONInstance {},
	mainJSON: class extends self.IJSONInstance {},
	languageCodeJSON: class extends self.IJSONInstance {},
	serverTimestampJSON: class extends self.IJSONInstance {},
	languageJSON: class extends self.IJSONInstance {},
	button: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Text: class extends self.ITextInstance {},
	Load_Bar_Back: class extends self.ITiledBackgroundInstance {},
	Load_Bar_Top: class extends self.ITiledBackgroundInstance {},
	popUpBoard: class extends self.IWorldInstance {},
	popUpBoard2: class extends self.IWorldInstance {},
	buttonIcon: class extends self.ISpriteInstance {},
	popUp: class extends self.ISpriteInstance {},
	GirlsDict: class extends self.IDictionaryInstance {},
	Gifts_All: class extends self.ISpriteInstance {},
	Gifts_All_PopUp: class extends self.ISpriteInstance {},
	BG_Location: class extends self.ISpriteInstance {},
	Ref_Lang: class extends self.ISpriteInstance {},
	Ref_Settings: class extends self.ISpriteInstance {},
	Spin_Icon: class extends self.ISpriteInstance {},
	Line_Horizontal: class extends self.ISpriteInstance {},
	ЗАГЛУШКА: class extends self.ITextInstance {},
	Ref_Girls: class extends self.ISpriteInstance {},
	Anim_Test: class extends self.ISpriteInstance {},
	AnimaTest: class extends self.ISpriteInstance {},
	TEstAnim: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Button2: class extends self.IButtonInstance {},
	Pop_Up: class extends self.ISpriteInstance {},
	Pop_Up_Mask: class extends self.ISpriteInstance {}
}